- name: Home
  columns:
    - size: small
      widgets:
        - type: clock
          hour-format: 24h
          timezones:
            - timezone: Europe/Kyiv
              label: Kyiv
            - timezone: Europe/Istanbul
              label: Istanbul
        - type: calendar
          first-day-of-week: monday
        - type: to-do
        - type: bookmarks
          groups:
            - title: Dev
              color: 263 57 75
              links:
                - title: Redmine
                  url: 'https://redmine.softerra.com/issues?query_id=79'
                - title: Workflowy
                  url: 'https://workflowy.com/'
                - title: Frontend
                  url: 'https://frontendfront.com/'
                - title: Pocket
                  url: 'https://pocketcasts.com/podcasts'
            - title: Spanish
              color: 10 70 50
              links:
                - title: Clozemaster
                  url: 'https://www.clozemaster.com/l/spa-eng'
                - title: Dreaming
                  url: 'https://app.dreaming.com/spanish/'
            - title: AI
              color: 200 50 50
              links:
                - title: Perplexity
                  url: 'https://www.perplexity.ai/'
                - title: Claude
                  url: 'https://claude.ai/'
                - title: Lumo
                  url: https://lumo.proton.me/  
            - title: Other
              color: 25 90 70
              links:
                - title: Jumble
                  url: 'https://jumble.social/'
                - title: Dashboard
                  url: 'https://dashboard.clarkmoody.com/'
                - title: iHerb
                  url: 'https://ua.iherb.com/'
                - title: Prom
                  url: 'https://prom.ua/'
    - size: full
      widgets:
        - type: group
          widgets:
            - type: rss
              title: WebDev
              style: vertical-list
              limit: 60
              collapse-after: 10
              feeds:
                - url: 'https://feeds.feedburner.com/CssTricks'
                  title: CSS-Tricks
                - url: 'https://frontendfront.com/feed/stories'
                  title: Front-end Front
                - url: 'https://developer.mozilla.org/en-US/blog/rss.xml'
                  title: MDN Blog
                - url: 'https://www.smashingmagazine.com/category/css/index.xml'
                  title: Smashing Magazine
                - url: 'https://frontendmasters.com/blog/feed/'
                  title: Frontend Masters
                - url: 'https://www.oddbird.net/feed.atom'
                  title: OddBird
                - url: 'https://daverupert.com/atom.xml'
                  title: daverupert
                - url: 'https://www.bram.us/feed/'
                  title: Bram.us
                - url: 'https://www.zachleat.com/web/feed/'
                  title: Zach Leatherman
                - url: 'https://piccalil.li/articles.xml'
                  title: Piccalil
            - type: rss
              title: Interesting
              style: vertical-list
              collapse-after: 10
              limit: 60
              feeds:
                - url: >-
                    https://www.damninteresting.com/feeds/damn-interesting-curated-links/
                  title: Damn Interesting Curated Links
                - url: 'https://www.popsci.com/feed'
                  title: Popular Science
        - type: group
          widgets:
            - type: videos
              title: Subs
              style: grid-cards
              collapse-after-rows: 3
              limit: 30
              channels:
                - UCtCqI5Q9Jyn5MtU_Oqo2e6g # gitana
                - UCWu6v5jfsW3wO948jOHMEiA # movesmethod
            - type: videos
              title: News
              style: grid-cards
              collapse-after-rows: 3
              limit: 30
              playlists:
                - PLtbZy7rFV41jK6TVlVQfrfW7CErEJpdij # popova
              channels:
                - UCCV5Z2DEYnUGIY_mO-AcQKw # grem
                - UCTVk323gzizpujtn2T_BL7w # breakfast
                - UCTY1dmeZ87bGv1dCv_jzMlQ # sheitelman
    - size: small
      widgets:
        - type: weather
          location: 'Kyiv, Ukraine'
          units: metric
          hour-format: 24h
        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: BTC-USD
              name: Bitcoin
        - type: custom-api
          title: Latest Community Widgets
          cache: 1d
          url: >-
            https://raw.githubusercontent.com/glanceapp/community-widgets/refs/heads/main/registry/widgets.json
          template: >
            <ul class="list list-gap-14 collapsible-container"
            data-collapse-after="3">
              {{ $widgets := .JSON.Array "" | sortByTime "time_added" "rfc3339" "desc" }}
              {{ if gt (len $widgets) 10 }}
                {{ $widgets = slice $widgets 0 10 }}
              {{ end }}
              {{ range $widgets }}
              <li>
                <a class="size-h4 block text-truncate color-primary-if-not-visited" href="https://github.com/glanceapp/community-widgets/blob/main/widgets/{{ .String "directory" }}/README.md" target="_blank" rel="noreferrer">{{ .String "title" }}</a>
                <p class="text-truncate-2-lines margin-top-3">{{ .String "description" }}</p>
                <ul class="list-horizontal-text margin-top-3">
                  <li {{ .String "time_added" | parseRelativeTime "rfc3339" }}></li>
                  <li>{{ .String "author" }}</li>
                </ul>
              </li>
              {{ end }}
            </ul>
